name: remoteStorage
description: Open protocol for per-user storage on the Web
url: http://remotestorage.io
highlights: true
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed
